name: My first workflow

on:
  pull_request:
    branches:
      - "main"
  push:
    - "main"

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
